// templates/svelte/src/components/TxSample.svelte
<script lang="ts">
  import { ConnectedWallet } from '@palomachain/wallet-controller';
  import { getController } from 'controller';
  import { Subscription } from 'rxjs';
  import { onDestroy, onMount } from 'svelte';
  import TxSampleForm from './TxSampleForm.svelte';

  let status: 'initializing' | 'not-connected' | 'can-not-post' | 'ready' = 'initializing';

  let connectedWallet: ConnectedWallet | undefined = undefined;
  let subscription: Subscription | null = null;

  onMount(() => {
    const controller = getController();

    subscription = controller.connectedWallet().subscribe((_connectedWallet) => {
      connectedWallet = _connectedWallet;

      if (_connectedWallet) {
        if (!_connectedWallet.availablePost) {
          status = 'can-not-post';
        } else {
          status = 'ready';
        }
      } else {
        status = 'not-connected';
      }
    });
  });

  onDestroy(() => {
    subscription?.unsubscribe();
    connectedWallet = undefined;
  });
</script>

<h1>
  Tx Sample
</h1>
{#if status === 'initializing'}
  <p>Initializing...</p>
{:else if status === 'can-not-post'}
  <p>This connection does not support post()</p>
{:else if status === 'not-connected'}
  <p>Wallet not connected!</p>
{:else if !!connectedWallet}
  <TxSampleForm connectedWallet={connectedWallet} />
{/if}

// templates/vue/src/components/TxSample.vue
<script setup lang="ts">
import { ConnectedWallet } from '@palomachain/wallet-controller';
import TxSampleForm from 'components/TxSampleForm.vue';
import { getController } from 'controller';
import { Subscription } from 'rxjs';
import { onMounted, onUnmounted, ref } from 'vue';

const status = ref<'initializing' | 'not-connected' | 'can-not-post' | 'ready'>(
  'initializing',
);

const connectedWallet = ref<ConnectedWallet | undefined>(undefined);

let subscription: Subscription | null = null;

onMounted(() => {
  const controller = getController();

  subscription = controller.connectedWallet().subscribe((_connectedWallet) => {
    connectedWallet.value = _connectedWallet;

    if (_connectedWallet) {
      if (!_connectedWallet.availablePost) {
        status.value = 'can-not-post';
      } else {
        status.value = 'ready';
      }
    } else {
      status.value = 'not-connected';
    }
  });
});

onUnmounted(() => {
  subscription?.unsubscribe();
});
</script>

<template>
  <h1>Tx Sample</h1>
  <p v-if="status === 'initializing'">Initializing...</p>
  <p v-else-if="status === 'can-not-post'">
    This connection does not support post()
  </p>
  <p v-else-if="status === 'not-connected'">Wallet not connected!</p>
  <TxSampleForm
    v-else-if="!!connectedWallet"
    v-bind:connected-wallet="connectedWallet"
  />
</template>
